"use client"
import UserHeader from "@/components/dashboard/user-header";

// export const metadata = {
//      title: 'Next.js',
//      description: 'Generated by Next.js',
// }
import "../globals.css";
import React from "react";

export default function RootLayout({ children }) {
     return (
          <html lang="en">

          <body>
          <UserHeader />
          {children}
          </body>
          </html>
     )
}
