"use client"
import Control_header from "@/components/panel/control_header";
import "../globals.css";
import ControlMenu from "@/components/panel/control_footer";
import React from "react";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }


export default function RootLayout({ children }) {
  return (
       <html lang="en">
       <body>
       <Control_header />
       {children}
       <ControlMenu />
       </body>
       </html>
  )
}
